# Generated by Django 2.2.2 on 2019-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drive/files')),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
