# Generated by Django 2.2.2 on 2019-06-17 09:58

from django.db import migrations, models
import drive.models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_auto_20190615_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=drive.models.files),
        ),
    ]
